print '.'

guests = [
  {
    first_name: "Shonna",
    last_name: "Dorsey",
    title: "",
    twitter: "shonna_dorsey",
    facebook: "shonna.dorsey.3",
    linkedin: "shonnadorsey",
    website: "interfaceschool.com",
    link_video: "http://www.youtube.com/watch?v=-_htr_QloS4",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-01-22 03:27:17".to_time,
    avatar_file_name: "shonna.jpeg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 24875,
    avatar_updated_at: "2015-01-22 03:27:12".to_time,
    slug: "shonna-dorsey",
    audio_file_name: "CoVis_Codex-Shonna_Dorsey.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 35489462,
    audio_updated_at: "2015-01-22 03:27:13".to_time,
    description: "In this episode we interview Shonna Dorsey from Interface Web School. Think you know Shonna? Tune in and find out!",
    show_notes: "Pet DNA testing - http://wisdompanel.com\r\n\r\nConversation Matters - http://squishtalks.com\r\n\r\nCoffee and Code - http://meetup.com/coffeeandcode"
  },
  {
    first_name: "Jimmy",
    last_name: "Winter",
    title: nil,
    twitter: "jimmywinter",
    facebook: "jimmywinter",
    linkedin: "jimmywinter",
    website: "",
    link_video: "http://www.youtube.com/watch?v=27jcJY8LTeY",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-02-09 02:52:59".to_time,
    avatar_file_name: "jimmy.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 24451,
    avatar_updated_at: "2015-02-09 02:52:55".to_time,
    slug: "jimmy-winter",
    audio_file_name: "Codex007-winter.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 16886887,
    audio_updated_at: "2015-02-09 02:52:56".to_time,
    description: "In this fun-filled episode, we learn exactly how hudl's Jimmy Winter broke his leg playing Guitar Hero.",
    show_notes: ""
  },
  {
    first_name: "Sandi",
    last_name: "Barr",
    title: nil,
    twitter: "sandikbarr",
    facebook: "sandi.k.barr",
    linkedin: "sandikbarr",
    website: "",
    link_video: "http://www.youtube.com/watch?v=vF1WQbLN9XE",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-02-01 19:46:37".to_time,
    avatar_file_name: "sandi.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 20712,
    avatar_updated_at: "2015-02-01 19:46:34".to_time,
    slug: "sandi-barr",
    audio_file_name: "Codex004-sandi.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 15771696,
    audio_updated_at: "2015-02-01 19:46:35".to_time,
    description: "In this episode, Omaha Coding Women's Sandi Barr tells us how she broke her face! Whaaaat??",
    show_notes: "Omaha Coding Women\r\nhttps://www.facebook.com/OmaCodingWomen\r\n\r\nLocal Omaha\r\nhttp://localomaha.org/\r\n\r\nNebraska Code Conference\r\nhttp://nebraskacode.com/"
  },
  {
    first_name: "Brian",
    last_name: "Smith",
    title: nil,
    twitter: "ListenBrian",
    facebook: "briansmith.biz",
    linkedin: "briantsmith",
    website: "briansmith.biz",
    link_video: "http://www.youtube.com/watch?v=KaWs5Brpjp0",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-02-01 22:46:39".to_time,
    avatar_file_name: "brian.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 18136,
    avatar_updated_at: "2015-02-01 22:46:34".to_time,
    slug: "brian-smith",
    audio_file_name: "Codex005-brain.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 24515659,
    audio_updated_at: "2015-02-01 22:46:35".to_time,
    description: "In this episode we talk to TEDxOmaha's Brian Smith and we figure out where downtown Omaha's stuffed animals come from. ",
    show_notes: "TEDx Omaha\r\nhttp://www.tedxomaha.com/\r\n\r\n"
  },
  {
    first_name: "Shane",
    last_name: "Reiser",
    title: nil,
    twitter: "shanereiser",
    facebook: "shanereiser",
    linkedin: "shanereiser",
    website: "startupgenome.co",
    link_video: "http://www.youtube.com/watch?v=qGqSR5sPdEY",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-01-26 03:22:58".to_time,
    avatar_file_name: "shane.png",
    avatar_content_type: "image/png",
    avatar_file_size: 221974,
    avatar_updated_at: "2015-01-26 03:22:52".to_time,
    slug: "shane-reiser",
    audio_file_name: "Codex003-Shane.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 54210415,
    audio_updated_at: "2015-01-26 03:22:53".to_time,
    description: "In this episode we talk to Stone Wonder (you probably know him as Shane Reiser) and we find out some of the songs on his karaoke playlist. \r\n\r\nBe sure to check out Startup Weekend in omaha! \r\nhttp://tinyurl.com/startupweekendomaha",
    show_notes: "Startup Weekend Omaha-Lincoln: \r\nhttp://tinyurl.com/startupweekendomaha\r\n\r\nathousandmiles by c.db.sn\r\nhttp://cdbsn.bandcamp.com/track/athousandmiles\r\n\r\nStartup Nebraska group\r\nhttps://www.facebook.com/groups/startupnebraska"
  },
  {
    first_name: "Rhegan",
    last_name: "Lundborg",
    title: nil,
    twitter: "rhegan",
    facebook: "rheganann",
    linkedin: "",
    website: "rhegan.me",
    link_video: "http://www.youtube.com/watch?v=M3_kWKFXexE",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-01-25 21:03:59".to_time,
    avatar_file_name: "rhegan.png",
    avatar_content_type: "image/png",
    avatar_file_size: 220645,
    avatar_updated_at: "2015-01-25 21:03:55".to_time,
    slug: "rhegan-lundborg",
    audio_file_name: "Codex002_rhegan.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 20967538,
    audio_updated_at: "2015-01-25 21:03:56".to_time,
    description: "In this episode we find out exactly how nimble yoga-master Rhegan Lundborg is at answering our questions. ",
    show_notes: ""
  },
  {
    first_name: "Michael",
    last_name: "Struthers",
    title: nil,
    twitter: "raptorstruthers",
    facebook: "raptorstruthers",
    linkedin: "michaelstruthers",
    website: "",
    link_video: "http://www.youtube.com/watch?v=8kkoB03FmQc",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-02-15 02:39:31".to_time,
    avatar_file_name: "struthers.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 56060,
    avatar_updated_at: "2015-02-15 02:39:26".to_time,
    slug: "michael-struthers",
    audio_file_name: "Codex008-struthers.mp3".to_time,
    audio_content_type: "audio/mp3",
    audio_file_size: 21084795,
    audio_updated_at: "2015-02-15 02:39:27".to_time,
    description: "In this episode, Flywheel's Michael Struthers explains to us his fondness for dinosaurs. ",
    show_notes: "Omaha Ruby Meetup\r\nhttp://meetup.com/Omaha-Ruby-Meetup"
  },
  {
    first_name: "Patrick",
    last_name: "Stevens",
    title: nil,
    twitter: "votersnapceo",
    facebook: "PatrickJohnStevens",
    linkedin: "patrickjohnstevens",
    website: "votersnap.com",
    link_video: "http://www.youtube.com/watch?v=bGnuq5e-kVQ",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-03-01 05:11:10".to_time,
    avatar_file_name: "patrick.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 135304,
    avatar_updated_at: "2015-03-01 05:11:06".to_time,
    slug: "patrick-stevens",
    audio_file_name: "Codex009-patrick.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 21343204,
    audio_updated_at: "2015-03-01 05:11:07".to_time,
    description: "In this episode we learn more about VoterSnap's Patrick John Stevens",
    show_notes: ""
  },
  {
    first_name: "Nick",
    last_name: "Nisi",
    title: nil,
    twitter: "nicknisi",
    facebook: "nicknisi",
    linkedin: "nicknisi",
    website: "",
    link_video: "http://www.youtube.com/watch?v=HehZ_73g8dc",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-02-07 21:31:38".to_time,
    avatar_file_name: "nisi.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 79504,
    avatar_updated_at: "2015-02-07 21:31:34".to_time,
    slug: "nick-nisi",
    audio_file_name: "Codex006-nisi.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 10384624,
    audio_updated_at: "2015-02-07 21:31:36".to_time,
    description: "In this episode we talk to Nick Nisi and find out why he had an eyebrow shaved off.",
    show_notes: "Nebraska JS conf\r\nhttp://nejsconf.com\r\n"
  },
  {
    first_name: "William",
    last_name: "Riley",
    title: nil,
    twitter: "Bill_Riley",
    facebook: "billoriley",
    linkedin: "",
    website: "williamriley.me",
    link_video: "http://www.youtube.com/watch?v=cyiw3f-i5vw",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-03-01 05:17:32".to_time,
    avatar_file_name: "will.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 30417,
    avatar_updated_at: "2015-03-01 05:17:30".to_time,
    slug: "william-riley",
    audio_file_name: "Codex010-will.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 23057466,
    audio_updated_at: "2015-03-01 05:17:30".to_time,
    description: "In this episode, we talk to the developer/designer who's doing way too many things, William Riley.",
    show_notes: "Tapped\r\nhttp://tappedapp.co\r\n\r\nNebraska AIGA\r\nhttp://nebraska.aiga.org\r\n\r\nHubdia\r\nhttp://hubdia.com/"
  },
  {
    first_name: "Andre",
    last_name: "Simones",
    title: nil,
    twitter: "asimones",
    facebook: "asimones",
    linkedin: "andresimones",
    website: "www.one80services.com",
    link_video: "http://www.youtube.com/watch?v=jJjtCJz_qMM",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-04-13 01:54:53".to_time,
    avatar_file_name: "andre.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 16390,
    avatar_updated_at: "2015-04-13 01:54:49".to_time,
    slug: "andre-simones",
    audio_file_name: "codex011-andre.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 27558338,
    audio_updated_at: "2015-04-13 01:54:49".to_time,
    description: "This week, Scrum Master Andre talks to us about his upcoming Startup Meetup.",
    show_notes: "Omaha Startups Meetup:\r\nhttp://one80services.com/event/startup-summit/\r\n\r\nAgile Foundations - Lincoln\r\nhttp://one80services.com/event/agile-foundations/\r\n\r\nAgile Foundations - Omaha\r\nhttp://one80services.com/event/agile-foundations-2/"
  },
  {
    first_name: "Dusty",
    last_name: "Reynolds",
    title: nil,
    twitter: "dreynolds41",
    facebook: "dusty.reynolds.10",
    linkedin: "dustyreynolds",
    website: "www.racenote.com",
    link_video: "http://www.youtube.com/watch?v=-LMN7gEgfN0",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-04-18 21:00:39".to_time,
    avatar_file_name: "dusty.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 8829,
    avatar_updated_at: "2015-04-18 21:00:36".to_time,
    slug: "dusty-reynolds",
    audio_file_name: "codex012-dustyr.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 18508477,
    audio_updated_at: "2015-04-18 21:00:37".to_time,
    description: "In this episode we talk to RaceNote's Dusty Reynolds. ",
    show_notes: ""
  },
  {
    first_name: "John",
    last_name: "Hobbs",
    title: nil,
    twitter: "jmhobbs",
    facebook: "jmhobbs85",
    linkedin: "johnhobbs",
    website: "www.velvetcache.org",
    link_video: "http://www.youtube.com/watch?v=wtDlFiIIY1o",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-04-26 23:20:17".to_time,
    avatar_file_name: "hobbs.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 116752,
    avatar_updated_at: "2015-04-26 23:20:14".to_time,
    slug: "john-hobbs",
    audio_file_name: "codex013-hobbs.mp3",
    audio_content_type: "audio/mp3",
    audio_file_size: 11636101,
    audio_updated_at: "2015-04-26 23:20:15".to_time,
    description: "Get to know Pack's John Hobbs!",
    show_notes: ""},
  {
    first_name: "Cara",
    last_name: "Heacock",
    title: nil,
    twitter: "caraheacock",
    facebook: "caraheacock",
    linkedin: "caraheacock",
    website: "",
    link_video: "http://www.youtube.com/watch?v=QwcJX3V0H5Q",
    link_audio: nil,
    photo: nil,
    date_uploaded: "2015-12-05 21:40:22".to_time,
    avatar_file_name: "twitter.jpg",
    avatar_content_type: "image/jpeg",
    avatar_file_size: 56060,
    avatar_updated_at: "2015-12-05 21:40:18".to_time,
    slug: "cara-heacock",
    audio_file_name: "codex014-cara.mp3".to_time,
    audio_content_type: "audio/mp3",
    audio_file_size: 22034783,
    audio_updated_at: "2015-12-05 21:40:19".to_time,
    description: "Cara joins us to talk about Discount Salmon and the cool meetup group, Side Projects Club.",
    show_notes: "Side Projects meetup:\r\nhttps://www.meetup.com/Side-Projects-Club/"
  }
]

guests.each do |guest|
  g = CodexGuest.find_by(twitter: guest[:twitter])
  unless g
    CodexGuest.create(guest)
  end
  print '.'
end
