default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: covisco_development

test:
  <<: *default
  database: covisco_test

production:
  <<: *default
  database: covisco_production
  username: covisco
  password: <%= ENV['COVISCO_DATABASE_PASSWORD'] %>
